version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - '27017:27017'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
